{% set version = "0.7.0" %}

package:
  name: django-typed-models
  version: {{ version }}

source:
  fn: django-typed-models-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-typed-models/django-typed-models-{{ version }}.tar.gz
  sha256: 21409c384a1705bf3998e7ad128b4f715c909d5dbd3dd98ee79a9aca32058916

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - django

test:
  imports:
    - typedmodels

about:
  home: http://github.com/craigds/django-typed-models
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Sane single table model inheritance for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
