travis:
  secure:
    BINSTAR_TOKEN: pKZcvcUw0ceZr0K6vGK3aBNIA3N9x0I7IstbmwIotG8EWkWwX8W5Y9nsDbZaZGcXTVlyACncgggv3hE4XzU4ohbpBxa+h+5A9r8Pm+JLSPOWjOAaOoWnkHKAlTilXeNd0fnfxDPjKNTZvT3ieg1ONRks2lj7eRQlyRYnAoZw3lvobuoJAJj8MhoTQeW+Joy1EPVTfb+lokU+8ecaKfZCgDOlwVoiMKdcXYfgxr/CFOKnoZwj4a8J3h09HusSoWSMGurm4rlRF8Nn0NlLYdWB/SillF1oOUZhcBIzyJMcOY2lo5lM4NYsHscIMSmHD8dU2BWrOtC6dAQ3tTRCDgWtNrT/PgkMlYus88W154Z5lPDmSGTOhUVbxgPA1E6mw7k/Zu8v9hBoFLGcI6bL0B09+3L3rnDqYHbVknVaFo5JuHLz1l0ZNdUz8Blk0MkxNuS2gks/pBC9UQKou+koznazXZ83gTJminNjXRspPelybN95ZxiCFX0lOYn2M2ikwDy0b1GZY6hMdRfphYd8857JLZ3yWz0bmaLoUoVvyvKVTImpVTwIuiv1vM+kmZuWnv4FvRa6RTWNePxvdKwj1UlVJ+afcyxNIarS4Df0NZkCQODaiVZasoj7iuUOwsk+/+1nijEySFuDid1EpkDo2IU6vFfYV/sdWF666WoFrJEFcdI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
